spring:
  output.ansi.enabled: always

  # mongo
  data.mongodb.uri: mongodb://localhost:27017/demo

  datasource:
    url: jdbc:h2:file:/data/demo
    username: sa
    # password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    properties:
      hibernate.format_sql: true
  # sql.init.mode: never
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

logging.level:
  org.hibernate:
    SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE
  org.springframework.jdbc.core:
    JdbcTemplate: DEBUG
    StatementCreatorUtils: TRACE


mail:
  host: smtp.gmail.com
  port: 587
  authEnabled: true
  starttlsEnabled: true
  protocol: smtp
  username: your_email_address
  password: your_email_password